version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    build:
      context: "."
      target: "dev"
    depends_on:
      - mongodb
    container_name: 'mvpcodingtest'
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      - JWT_TOKEN_SECRET=JWT_TOKEN_SECRET
      - DB_URL = mongodb://mongodb:27017/demo
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  db-data: